#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J RNA_trim_GA
#SBATCH -t 4:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user jay.hakansson.4449@student.uu.se

#for troubleshooting
set -x

cat $0
echo QOS = $SLURM_JOB_QOS

#work in node-local storage
cd $SNIC_TMP

#Load modules
module load bioinfo-tools trimmomatic

#Copy adapter file here
cp $HOME/genome_analysis_project/Genome-Analysis-VT22/analyses/01_preprocessing/illumina_adapters.fa illumina_adapters.fa

#For D1RNA
java -jar /sw/bioinfo/trimmomatic/0.39/snowy/trimmomatic-0.39.jar PE -threads 16 -trimlog D1RNA_trim.log /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/RNA_untrimmed/SRR4342137.1.fastq.gz /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/RNA_untrimmed/SRR4342137.2.fastq.gz -baseout D1RNA_trimmed.fq.gz ILLUMINACLIP:illumina_adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50
#For D3RNA
java -jar /sw/bioinfo/trimmomatic/0.39/snowy/trimmomatic-0.39.jar PE -threads 16 -trimlog D3RNA_trim.log /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/RNA_untrimmed/SRR4342139.1.fastq.gz /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/RNA_untrimmed/SRR4342139.2.fastq.gz -baseout D3RNA_trimmed.fq.gz ILLUMINACLIP:illumina_adapters.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50

#Copy outfiles to correct folder
cp *.gz $HOME/genome_analysis_project/Genome-Analysis-VT22/data/trimmed_data/RNA_trimmed_12-04
