#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J megahit_D1DNA_04-18
#SBATCH -t 7:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user jay.hakansson.4449@student.uu.se


#for troubleshooting
set -x

cat $0
echo QOS = $SLURM_JOB_QOS

#work in node-local storage
cd $SNIC_TMP
module load bioinfo-tools megahit

cp /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/DNA_trimmed/SRR4342129_1.paired.trimmed.fastq.gz D1DNA_trimmed_1.fastq.gz
cp /proj/genomeanalysis2022/Genome_Analysis/3_Thrash_2017/DNA_trimmed/SRR4342129_2.paired.trimmed.fastq.gz D1DNA_trimmed_2.fastq.gz

megahit --kmin-1pass --k-min 65  --k-max 105 --k-step 10 -1 D1DNA_trimmed_1.fastq.gz -2 D1DNA_trimmed_2.fastq.gz -o $HOME/genome_analysis_project/Genome-Analysis-VT22/data/assembly/D1DNA_assembly/megahit_04-18
