#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J rna_mapping_bwa
#SBATCH -t 06:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user jay.hakansson.4449@student.uu.se

#print script
cat $0

export D3BINS=$HOME/genome_analysis_project/Genome-Analysis-VT22/analyses/03_binning/D3DNA_bins/final.contigs.fa.metabat-bins
export D1BINS=$HOME/genome_analysis_project/Genome-Analysis-VT22/analyses/03_binning/D1DNA_bins/final.contigs.fa.metabat-bins
export RNA=$HOME/genome_analysis_project/Genome-Analysis-VT22/data/trimmed_data/RNA_trimmed_12-04
export OUT=$HOME/genome_analysis_project/Genome-Analysis-VT22/analyses/05_RNA_mapping

#Load modules
module load bioinfo-tools bwa samtools

cd $D1BINS
for infile in *.fa
do
# bwa index $infile
 bwa mem -t 2 $infile $RNA/D1RNA_trimmed_1P.fq.gz $RNA/D1RNA_trimmed_2P.fq.gz | samtools view -@ 2 -b - > $SNIC_TMP/${infile}_RNA_map.bam 
 samtools sort $SNIC_TMP/${infile}_RNA_map.bam -o $OUT/D1_maps/${infile}_RNA_map_sorted.bam
done

cd $D3BINS
for infile in *.fa
do
 bwa index $infile
 bwa mem -t 2 $infile $RNA/D3RNA_trimmed_1P.fq.gz $RNA/D3RNA_trimmed_2P.fq.gz | samtools view -@ 2 -b - > $SNIC_TMP/${infile}_RNA_map.bam
 samtools sort $SNIC_TMP/${infile}_RNA_map.bam -o $OUT/D3_maps/${infile}_RNA_map_sorted.bam
done
