#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J D3RNA_trim_FASTQC
#SBATCH -t 15:00 --qos=short
#SBATCH --mail-type=ALL
#SBATCH --mail-user jay.hakansson.4449@student.uu.se

#Run FASTQC on my trimmomatic output files

#for troubleshooting
set -x

cat $0
echo QOS = $SLURM_JOB_QOS

#work in node-local storage
cd $SNIC_TMP

module load bioinfo-tools FastQC

#Copy trimmomatic files here
cp -r $HOME/genome_analysis_project/Genome-Analysis-VT22/data/trimmed_data/RNA_trimmed_12-04 RNA_trimmed_12-04

cd RNA_trimmed_12-04/

fastqc D3RNA_trimmed_1P.fq.gz  D3RNA_trimmed_1U.fq.gz  D3RNA_trimmed_2P.fq.gz  D3RNA_trimmed_2U.fq.gz -o $HOME/genome_analysis_project/Genome-Analysis-VT22/analyses/01_preprocessing/fastqc_trim/RNA_12-04
